[package]
name = "arc-geometry"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }

[dependencies]
arc-core = { path = "../arc-core" }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
nalgebra = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
truck-base = { workspace = true }
truck-geometry = { workspace = true }
truck-topology = { workspace = true }
truck-modeling = { workspace = true }
truck-polymesh = { workspace = true }
truck-meshalgo = { workspace = true }
truck-stepio = { workspace = true }
monstertruck-fillet = { workspace = true }
monstertruck-healing = { workspace = true }
bytemuck = { workspace = true }
gltf = { workspace = true }
dxf = { workspace = true }

[features]
default = []
